### ISSUE TITLE
jmalloc is not being used

### ISSUE THREAD

**Issue by grosser** [cblunt/alpine-linux-ruby-dockerfile#1]
FYI just tried this and jmalloc is not active ... so kinda useless

`ruby -r rbconfig -e "RbConfig::CONFIG['LIBS'].include?('jemalloc') ? puts('Ruby is compiled with jemalloc') : warn('JEMALLOC IS MISSING FROM RUBY')"`

also FYI virtual apk packages help cleaning up `apk add --update --no-cache --virtual ruby-dependencies foo bar` + `apk del ruby-dependencies \`

**Comment by cblunt** [comment]
Thanks for letting me know. I'm going to update the readme to deprecate this repo as I [now recommend](https://www.chrisblunt.com/rails-on-docker-getting-started-docker-ruby-rails/) using the official [ruby alpine](https://hub.docker.com/_/ruby/) images (e.g. `docker pull ruby:2.4-alpine`).

There is a [pull request](https://github.com/docker-library/ruby/pull/198) to add jemalloc support to the official images, although it looks like [alpine is not an option](https://github.com/docker-library/ruby/pull/198#issuecomment-373264955) due to a [bug with ruby/alpine/jemalloc](https://bugs.ruby-lang.org/issues/13524).
